<a href="https://colab.research.google.com/github/SamarBaghdadi/CodingDojo_DS_V23/blob/new-main-branch/Slicing_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
fname='/content/drive/MyDrive/CodingDojo/01-Fundamentals/Week02/Data/bake-sale-data.csv'
df =pd.read_csv(fname)
df.head()

,Item,Student,Packaging,Price,Expense,Profit per Item,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
0,brownie,Hugo,Individually Wrapped (Plastic),2.25,0.25,2.00,17,19,25,25
1,cookie,Sally,Individually Wrapped (Plastic),1.25,0.50,0.75,40,32,38,38
2,cake,Martina,Boxed (Clear Plastic),9.50,5.00,4.50,1,2,0,0
3,cupcake,Joe,Boxed (Cardboard),3.50,0.75,2.75,10,14,12,12
4,fudge,Hugo,Individually Wrapped (Foil),3.00,1.00,2.00,0,20,22,22

In [5]:
df['Item']

0                  brownie
1                   cookie
2                     cake
3                  cupcake
4                    fudge
5             banana bread
6                    torte
7                    scone
8                   muffin
9     rice krispies treats
10               apple pie
11            key lime pie
Name: Item, dtype: object

In [6]:
df[['Item','Price']]

                    Item  Price
0                brownie   2.25
1                 cookie   1.25
2                   cake   9.50
3                cupcake   3.50
4                  fudge   3.00
5           banana bread   2.75
6                  torte  10.50
7                  scone   2.00
8                 muffin   1.50
9   rice krispies treats   1.25
10             apple pie  10.00
11          key lime pie   9.50

In [7]:
df.loc[2]

Item                                      cake
Student                                Martina
Packaging                Boxed (Clear Plastic)
Price                                      9.5
Expense                                    5.0
Profit per Item                            4.5
Quantity Sold (Day 1)                        1
Quantity Sold (Day 2)                        2
Quantity Sold (Day 3)                        0
Quantity Sold (Day 4)                        0
Name: 2, dtype: object

In [8]:
type(df.loc[2])

pandas.core.series.Series

In [9]:
type(df.loc[[2]])

pandas.core.frame.DataFrame

In [17]:
#Change the index
df=df.set_index("Item")
df.head()

KeyError: "None of ['Item'] are in the columns"

In [18]:
df

,Student,Packaging,Price,Expense,Profit per Item,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
Item,,,,,,,,,
brownie,Hugo,Individually Wrapped (Plastic),2.25,0.25,2.00,17,19,25,25
cookie,Sally,Individually Wrapped (Plastic),1.25,0.50,0.75,40,32,38,38
cake,Martina,Boxed (Clear Plastic),9.50,5.00,4.50,1,2,0,0
cupcake,Joe,Boxed (Cardboard),3.50,0.75,2.75,10,14,12,12
fudge,Hugo,Individually Wrapped (Foil),3.00,1.00,2.00,0,20,22,22
banana bread,Mark,Individually Wrapped (Foil),2.75,0.50,2.25,0,10,13,13
torte,Jade,Boxed (Clear Plastic),10.50,5.50,5.00,0,5,7,7
scone,Jade,Individually Wrapped (Plastic),2.00,1.25,0.75,0,8,10,10
muffin,Anne,Individually Wrapped (Foil),1.50,0.75,0.75,0,3,4,4
rice krispies treats,Martina,Individually Wrapped (Plastic),1.25,0.25,1.00,0,0,10,30
apple pie,Sally,Box (Cardboard),10.00,4.00,6.00,0,0,2,3
key lime pie,Martina,Box (Cardboard),9.50,4.50,5.00,0,0,3,3

In [11]:
s=df.loc['cake']

In [12]:
type(s.loc[['Price']])

pandas.core.series.Series

In [14]:
df.loc['muffin',['Price','Student']]

Price       1.5
Student    Anne
Name: muffin, dtype: object

In [20]:
df.loc[['muffin','scone','banana bread'],['Price','Expense','Student']]

              Price  Expense Student
Item
muffin         1.50     0.75    Anne
scone          2.00     1.25    Jade
banana bread   2.75     0.50    Mark

In [23]:
#df.loc[['Price','Expense','Student'],['muffin','scone','banana bread']]
#This wont work, because the .loc needs an index in the rows
df.index

Index(['brownie', 'cookie', 'cake', 'cupcake', 'fudge', 'banana bread',
       'torte', 'scone', 'muffin', 'rice krispies treats', 'apple pie',
       'key lime pie'],
      dtype='object', name='Item')

In [25]:
rows_to_slice=['muffin','scone','banana bread']
columns_to_slice=['Price','Expense','Student']
df.loc[rows_to_slice,columns_to_slice]

              Price  Expense Student
Item
muffin         1.50     0.75    Anne
scone          2.00     1.25    Jade
banana bread   2.75     0.50    Mark

In [26]:
#if we want to slice a column for all the rows,
df.loc[:,'Expense']

Item
brownie                 0.25
cookie                  0.50
cake                    5.00
cupcake                 0.75
fudge                   1.00
banana bread            0.50
torte                   5.50
scone                   1.25
muffin                  0.75
rice krispies treats    0.25
apple pie               4.00
key lime pie            4.50
Name: Expense, dtype: float64

In [28]:
df.loc[:,['Expense',"Price"]]

                      Expense  Price
Item
brownie                  0.25   2.25
cookie                   0.50   1.25
cake                     5.00   9.50
cupcake                  0.75   3.50
fudge                    1.00   3.00
banana bread             0.50   2.75
torte                    5.50  10.50
scone                    1.25   2.00
muffin                   0.75   1.50
rice krispies treats     0.25   1.25
apple pie                4.00  10.00
key lime pie             4.50   9.50

In [30]:
#slice a price for a particular index and change it, use .loc
df.loc['torte','Price']=11.5

In [32]:
df.loc['torte',['Price','Expense']]

Price      11.5
Expense     5.5
Name: torte, dtype: object